### ISSUE TITLE
Rework timeseries creation to contain species with observation after 1950 

### ISSUE THREAD

**Issue by SanderDevisscher** [inbo/aspbo#199]
Currently species introduced prior to 1950 are excluded from the GAM timeseries this should be reworked to match option 2 of https://github.com/inbo/alien-species-portal/pull/74#issuecomment-2191167596. ea species should be included in the timeseries if they have at least 1 observation after 1950 independent of their year of introduction. This means the logic discribed here should be reworked.

https://github.com/inbo/aspbo/blob/ea385cec983aeddadf47cd7785112ad4c4c53730/src/05_occurrence_indicators_preprocessing.Rmd#L374

**Comment by soriadelva** [comment]
I've altered the code but @SanderDevisscher could you run the upload of the timeseries to the S3-bucket because I don't get permission to do that (still the same error as before)? Also I changed the name of one of the output files in the data/output folder from taxa_introduced_in_BE_before_1950.tsv to taxa_last_observed_in_BE_before_1950.tsv, but I'm not sure whether this may be throwing errors downstream. According to #135 this file has to be placed in the interim folder so it may be fine.

**Comment by mvarewyck** [comment]
We don't use that file `taxa_introduced_in_BE_before_1950.tsv`, so for me renaming is fine.

**Comment by SanderDevisscher** [comment]
> We don't use that file `taxa_introduced_in_BE_before_1950.tsv`, so for me renaming is fine.

=> #135 remains TRUE

**Comment by SanderDevisscher** [comment]
> I've altered the code but @SanderDevisscher could you run the upload of the timeseries to the S3-bucket because I don't get permission to do that (still the same error as before)? Also I changed the name of one of the output files in the data/output folder from taxa_introduced_in_BE_before_1950.tsv to taxa_last_observed_in_BE_before_1950.tsv, but I'm not sure whether this may be throwing errors downstream. According to #135 this file has to be placed in the interim folder so it may be fine.

@soriadelva you can allways trigger the workflow from a branch, see https://github.com/inbo/aspbo/actions/workflows/update_indicators_preprocessing.yaml. As long as you run it from `uat` afterwards.

**Comment by soriadelva** [comment]
> > I've altered the code but @SanderDevisscher could you run the upload of the timeseries to the S3-bucket because I don't get permission to do that (still the same error as before)? Also I changed the name of one of the output files in the data/output folder from taxa_introduced_in_BE_before_1950.tsv to taxa_last_observed_in_BE_before_1950.tsv, but I'm not sure whether this may be throwing errors downstream. According to #135 this file has to be placed in the interim folder so it may be fine.
> 
> @soriadelva you can allways trigger the workflow from a branch, see https://github.com/inbo/aspbo/actions/workflows/update_indicators_preprocessing.yaml. As long as you run it from `uat` afterwards.

@SanderDevisscher ik krijg die workflow precies niet te zien als ik onder actions kijk 🤔

**Comment by soriadelva** [comment]
This Github Actions keeps on throwing errors and it seems to go wrong after the timeseries (df_ts) is uploaded to the S3 bucket:
![action_cancellation](https://github.com/inbo/aspbo/assets/158742062/7b246758-ed4e-45f9-9ba9-2e72776c07af) This step cannot be executed:
`alienSpecies::createTimeseries(
  shapeData = alienSpecies::loadShapeData("grid.RData")$utm1_bel_with_regions, 
  bucket = UAT_bucket)`
 The changes I did on this branch cause the timeseries file to be much larger than before (51 397 730 rows instead of 16 601 399).  Could it be that this file is too heavy and causes the workflow to get cancelled?

**Comment by soriadelva** [comment]
@mvarewyck I did a test this morning, rewriting the createTimeseries function (within the 05_occurrence_indicators... .Rmd , not the original function in the alien-species-portal repo) so it would merge the df_ts data with shapeData in chunks of rows instead of all at once and this fixed the issue. Could you rewrite the original function in the way you'd prefer so that it could efficiently do this merge for a large file?

**Comment by mvarewyck** [comment]
> @mvarewyck I did a test this morning, rewriting the createTimeseries function (within the 05_occurrence_indicators... .Rmd , not the original function in the alien-species-portal repo) so it would merge the df_ts data with shapeData in chunks of rows instead of all at once and this fixed the issue. Could you rewrite the original function in the way you'd prefer so that it could efficiently do this merge for a large file?

@soriadelva I've implemented a fix for efficient joining in the [alienspecies v1.0.0](https://github.com/inbo/alien-species-portal/blob/fix_v1.0.0/alienSpecies/R/data_create.R#L174-L185) which works for me locally. Can you check whether it works on your side? Otherwise can you send me the code to do it chunk-wise as I don't know how large the chunks can be to make it work.

**Comment by soriadelva** [comment]
> > @mvarewyck I did a test this morning, rewriting the createTimeseries function (within the 05_occurrence_indicators... .Rmd , not the original function in the alien-species-portal repo) so it would merge the df_ts data with shapeData in chunks of rows instead of all at once and this fixed the issue. Could you rewrite the original function in the way you'd prefer so that it could efficiently do this merge for a large file?
> 
> @soriadelva I've implemented a fix for efficient joining in the [alienspecies v1.0.0](https://github.com/inbo/alien-species-portal/blob/fix_v1.0.0/alienSpecies/R/data_create.R#L174-L185) which works for me locally. Can you check whether it works on your side? Otherwise can you send me the code to do it chunk-wise as I don't know how large the chunks can be to make it work.

@mvarewyck I tested your fix and it works, thanks a lot! I'll rewrite the code in the 05_occurrence_indicators... .Rmd so it calls upon this function again.
